### ISSUE TITLE
Need help. Twizy charger issue

### ISSUE THREAD

**Issue by Kamsta99** [dexterbg/Twizy-Virtual-BMS#2]
Hi, my twizy is stuck charging at max 5A, tried a lot off settings and a lot of BMS (Blazej BMS, KlausBMS,  SimpleBMS). Unfortunely im still not so advanced in coding on Arduino, but i changed setChargeCurrent() value to 10 A min in code to make sure but no success. Charging percentage are not updated, i need to switch off->on. Any sugestions ?

**Comment by dexterbg** [comment]
That sounds pretty confused. You normally cannot simply switch the software without understanding how they each work and what they need.

SimpleBMS uses a voltage reading to derive SOC, and the SOC to derive the allowed charge current. So if the voltage reading isn't configured correctly or doesn't work, both SOC and charge current will likely also not work. BlazejBMS is tailored to a 4 "cell" lead acid configuration, and KlausBMS to a 16 cell LFP setup.

All example implementations do extensive logging via serial. My suggestions are:
a) describe your setup
b) provide the debug log

**Comment by Kamsta99** [comment]
At first i want to thank you for reply, i done battery using Li-Ion batteries LEV40 14cellsx3. Everything except charging works fine (driving no errors).
![20190930_223108](https://user-images.githubusercontent.com/8656801/66274350-0346b680-e87e-11e9-8fcc-61e29dd35726.jpg)
I did case for batteries.
![20190930_223216](https://user-images.githubusercontent.com/8656801/66274372-456ff800-e87e-11e9-98d3-1693fc38e97a.jpg)
Also using oryginal sockets
![69564446_428234047824613_1407412494581891072_n](https://user-images.githubusercontent.com/8656801/66274397-8405b280-e87e-11e9-892d-4a9e105fcf65.jpg)
No errors on LCD

**Comment by Kamsta99** [comment]
Also i got these debugs when charging
![Screenshot_20191006-212037](https://user-images.githubusercontent.com/8656801/66274461-48b7b380-e87f-11e9-990b-127dff5e090e.png)
We are using buildin charger
![71693504_387887638789330_3866996856043077632_n](https://user-images.githubusercontent.com/8656801/66274478-84527d80-e87f-11e9-871a-df7eaa163db8.jpg)

**Comment by dexterbg** [comment]
Nice images, but without any substantial info on your actual setup.

a) Do you use a real BMS or the Arduino as the BMS?
b) How do you read the battery sensors, which sensors do you have?
c) Your log only shows the VirtualBMS core debug output, where are the debug outputs of the BMS model chosen?
d) And which one is that now? And how is it configured / modified for your hardware?

**Comment by Kamsta99** [comment]
a) Im using Arduino Nano as BMS
b) We did voltage divider from 60V ->4,5V like note in code also made check did  vcore show same result like voltage meter
c) I got log only in idle state Vcore, soc and temp looking at code i should have more ... 
d) I had most success on SimpleBMS, there files, i changed battery voltage 
[SimpleBMS.zip](https://github.com/dexterbg/Twizy-Virtual-BMS/files/3694847/SimpleBMS.zip)

**Comment by dexterbg** [comment]
OK, that gets us one step further. Now I need the actual full log output of a charge attempt.
The SimpleBMS log should show the measurements and data derived from the measurements once per second from bmsTicker().

**Comment by Kamsta99** [comment]
There is everything i got via log
https://www.youtube.com/watch?v=UT8BhkOUG44&list=LLmkOltXakQK5IzsuK87Dk0A&index=2

**Comment by dexterbg** [comment]
OK, there's a bug in the SimpleBMS bmsTicker function.
In SimpleBMS.ino, please change the ticker line 107 from…
```C
  if (twizy.inState(Off) && (clockCnt % 100 == 0)) {
```
…to…
```C
  if (!twizy.inState(Off) && (clockCnt % 100 == 0)) {
```
…then get another log.

**Comment by dexterbg** [comment]
As the whole ticker did only run in state "Off", that may have been the cause for your issue with SimpleBMS as well.

But that bug is only present in SimpleBMS, not in BlazejBMS or KlausBMS, so let's see where you get now.

**Comment by Kamsta99** [comment]
WOAH 32A charging working and percentage goes up. Grab my generous donate.

**Comment by Kamsta99** [comment]
Nah i miss comment section in donate. I dont want to anonymous but Kamsta99 👍

**Comment by dexterbg** [comment]
You're welcome. Please send images of the build process and final result if you'd like me to include your build as another showcase.

**Comment by Kamsta99** [comment]
History:
![zdj](https://dl3.pushbulletusercontent.com/tgvuR6CosRdxH5eLc9kuWFebBHVrYr5b/20190815_202812.jpg)
Trying to understand how arduino works 
![zdj1](https://dl3.pushbulletusercontent.com/iGrAU85naZRIOcvgQ866JFKJROkRwXkn/20190831_203701.jpg)
also some hardware problems we cant get GO light at first

**Comment by dexterbg** [comment]
Please collect everything as a ZIP and send me that by email for the inclusion. Thanks!

**Comment by abdurauf16** [comment]
my twizy is off but stop and n are on

**Comment by abdurauf16** [comment]
hello, I have a twizy on the ride, the light is off, the go light is on, stop can, or you will send a sketch for acid batteries for a renault twisi

**Comment by abdurauf16** [comment]
hello, I have a twizy on the ride, the light is off, the go light is on, stop can, or you will send a sketch for acid batteries for a renault twizy please help me dwxterberg please help

**Comment by Abdurauf1234** [comment]
pleas help how to do virtual bms

**Comment by Abdurauf1234** [comment]
I bought a Renault Tweezy without BMS and for 4 years I can’t make a virtual BMS, I can make a video on how to make your first virtual BMS based on acid batteries, I would buy a Renault Twizy accumulator, but I need to bring it from Korea if it will cost about 2000 to bring it from Korea to our country $ 3000 and in our country on average they earn $ 200 help please make a virtual BMS from acid batteries, you can throw off the connection diagram of the components
