### ISSUE TITLE
Hi Dexter again i have problem with SimpleBMS ...

### ISSUE THREAD

**Issue by Kamsta99** [dexterbg/Twizy-Virtual-BMS#3]
Hi friend, i need help a little bit, Twizy driving fine but my charger sometimes randomly shutdown ... solution is to just unplug and plug again, but this force to babysit your car, is there any possible solution via code ? Someting like loop to start charging again if SOC below value ? Im not scripter or coder sadly.
[SimpleBMS.zip](https://github.com/dexterbg/Twizy-Virtual-BMS/files/4178125/SimpleBMS.zip)

**Comment by dexterbg** [comment]
Great to hear it still works.

There is most probably a simple solution to this, but we should first get a clue about the reason for the aborts. Can you provide a debug log (`TWIZY_DEBUG_LEVEL` set to 2) of a charge process including an abort event?

Do you use the original Renault charger? Many Twizy have issues with the first generation of these. Maybe your charger is about to die. Most issues result from the charger getting too hot, in some cases it could be traced down to a blocked/malfunctioning fan. Did you check if the fan works normally?

You also should open and check the connector from the charger to the battery, there have been reports of these corroding / burning / melting.

**Comment by Kamsta99** [comment]
Glad to hear you :D
Im using original charger
![71693504_387887638789330_3866996856043077632_n](https://user-images.githubusercontent.com/8656801/74273017-fba58b80-4d0f-11ea-8c99-92baa252fc9c.jpg)
Charger was dismantled and cleaned including fan, so everything is clean. 
 I will try to record this log today but its totaly random

**Comment by dexterbg** [comment]
Yes, that's version 06 from 2013, IIRC still the first generation (second begins with Ind 08).
Fingers crossed it doesn't die now, you certainly won't get a replacement on warranty…

**Comment by Kamsta99** [comment]
I cant reproduce problem now, today charging without shutdown as i say its random. Did you have idea how to fix this by extra bits of code ? Code seems less expensive than charger 😁

**Comment by Kamsta99** [comment]
Hi after a longer while, i tried debug mode 2 but using this make my car unable to drive or charge, after dump everything crash (like after 10 seconds after run). My charger from 2013 likely died some days ago, i installed another which i bought from internet, charger from 2016, everything working well but still finish charging before reaching 100% )but still better because less frequent), any ideas ?

**Comment by dexterbg** [comment]
Well, if you bought a used charger, you cannot know if that doesn't have the same issue already…
Debug mode 2 normally works, no idea about the crash. Regarding the charge stops, another (maybe better) option would be a separate CAN log.

**Comment by Kamsta99** [comment]
Debug mode 2 make my twizy not able to charge or drive, when dump appear via bluetooth GO light disappear and if trying to drive km/h also. Charger (new one) working well, sometimes shutdown near 80%-90%. Separate can log how to do that ?

**Comment by dexterbg** [comment]
Use some separate CAN logging device. Needs to be capable of 500 kbit CAN logging. You can use my https://github.com/dexterbg/CanLogger, but take care to turn on compiler speed optimization, comment out the logic inputs, and/or use a faster Arduino board.

**Comment by Kamsta99** [comment]
I have no clue how to do that, tried some things, but no success. I started to doing code solution.
`    }
    if (twizy.isPluggedIn() == 1) {
      if (twizy.inState(Off) && (soc <= 98)) {
        Serial.print(F("bmsEnterState: forcing charging "));
        twizy.enterState(StartCharge);
      }
    }`
![obraz](https://user-images.githubusercontent.com/8656801/80282983-da501b00-8714-11ea-99dd-696de4e15755.png)

I got success, i see by bluetooth bmsEnterState: forcing charging only if plugged in and offbut how to change status from Off to Charging

**Comment by Kamsta99** [comment]
Changed code a bit got 3MW working, but still keeps staing in off state
![obraz](https://user-images.githubusercontent.com/8656801/80292292-f88a3b00-8755-11ea-991a-a0ab90e4f080.png)
![Screenshot_20200425-231245](https://user-images.githubusercontent.com/8656801/80292303-13f54600-8756-11ea-8c7f-58901e0b5273.png)

**Comment by dexterbg** [comment]
Are you trying to (re-)start the charge from the BMS? That will not work. The BMS doesn't start the charge, the charger does. The BMS can tell the charger to reduce current or stop, but not to start.

My idea was there is possibly something causing a stop charge command, but you should see that in the BMS log. If you don't, the charger stops by itself, and then the BMS cannot do anything about that.

There's just one slight possibility that may also cause the charger to abort: if your Arduino has a timing issue, i.e. cannot sustain exact 10 ms intervals for the communication. See config #define TWIZY_CAN_CLOCK_US. Try reducing and increasing this in small steps around the default of 10000.

**Comment by Kamsta99** [comment]
Problem happen unfortunnelly on 4 different complete arduino boards. So probablly its not timing issue but i will try, thats last way i got now before doing something like hardware solution

**Comment by dexterbg** [comment]
I still think you need to capture a debug log and/or CAN log of an abort event first to get a hint about the source of the issue.

**Comment by Kamsta99** [comment]
https://streamable.com/ivw80g
This is how this looks on twizy debugmode 2
Still no can logging sadly

**Comment by Abdurauf1234** [comment]
Hello l have Renault twizy but not bms how to do simple l make simple bms but don.t working

**Comment by Abdurauf1234** [comment]
how to make a virtual bms for tweezy acid or gel I need a virtual bms for the answer please

**Comment by Abdurauf1234** [comment]
don.t close please

**Comment by Abdurauf1234** [comment]
you have instagram or facebook please help

**Comment by Abdurauf1234** [comment]
I bought a Renault Tweezy without BMS and for 4 years I can’t make a virtual BMS, I can make a video on how to make your first virtual BMS based on acid batteries, I would buy a Renault Twizy accumulator, but I need to bring it from Korea if it will cost about 2000 to bring it from Korea to our country $ 3000 and in our country on average they earn $ 200 help please make a virtual BMS from acid batteries, you can throw off the connection diagram of the components

**Comment by Abdurauf1234** [comment]
please help

**Comment by Abdurauf1234** [comment]
my email abduraufvaliev@gmail.com

**Comment by Abdurauf1234** [comment]
dexterberg
