### ISSUE TITLE
Start signal fault

### ISSUE THREAD

**Issue by Rox50055** [dexterbg/Twizy-Virtual-BMS#4]
Hello!
Thanks to your code we got super far with our twizy! most fault codes are gone, but some annoying ones stick. 

The first one is like the title: Start signal Fault P0412.
Along that code we also got: Power supply relay Fault P0218. We got a relay connected to the Sevcon relay wires on the plug coming from the Twizy.
The red STOP light is on and and the battery logo with ! on it, no ERROR though.

For now we are just connecting the bare minimum to test if it still works but to no success yet.
I was wondering if you might know a fox for this issue?

Hope to hear from you soon!
Greetings Kenneth

**Comment by dexterbg** [comment]
Kenneth,

the fault sounds like you only connected only one of the SEVCON supply relays.

I've attached a draft of the Uno example extended by the Yazaki plug and relays. Check your setup against this.

Regards,
Michael

![Arduino-Example-Yazaki-Relays](https://user-images.githubusercontent.com/2706753/78421171-eab13080-7655-11ea-9177-db2507ea21e2.png)

**Comment by Rox50055** [comment]
Thanks for the reply!
Making these connections solved the No start signal problem. But sadly the twizy still doesnt work.

We now got the fault P0216/DF181 "Power Relay Charger" and it wont activate the relays to power the sevcon or or other components. When I have my can reader attached with live data I can see the states of all relays and by default it's Open and when I manually power it, it switches to Closed. Meaning that the feedback works. 

My thought is that the charger is not giving out the OK signal for it to work or not getting all the proper information. It is a Twizay and charger from 2012, so there shouldn't be any software locks.

I hope that you might know a solution to this!
Thanks in advance

Best regards, 
Kenneth

**Comment by dexterbg** [comment]
The charger power relay is controlled directly by the charger, it's normally activated during the startup handshake with the BMS (not sure at which step, but I'd guess immediately after the initial communication). Compare the handshake to the protocol document. If the handshake looks normal, there must be some electrical fault. Check all wiring, connections and fuses involved.

**Comment by Tudy1983** [comment]
Can have the code please compiled I'm trying to figure out how this is done I'm new in this project I'm still learning like this I can make my own battery  thanks

**Comment by Rox50055** [comment]
Hey. 
Sadly we have determent that the charger is broken (it's the oldest model) and that's why it doesn't work. The new problem is that we can't find a new, old one that will work with the VBMS you wrote according to what I read on your pages. (The 2016+ models)

We also tried to control  the sevcon direcly with no success since it's also expects a Clear from over the canbus. 

I do not have the equipment or know how to decode canbus signals, nor do we have a working twizy. Maybe you know a way to remove the charger completely out the system? 

Hope to hear from you soon again! 
If this way doesn't work than we probably have to just get rid of it all and get a universal ESC/Motor controller.

Best regards, 
Kenneth

**Comment by Tudy1983** [comment]
Wath I was mean is the code for arduino I'm tryna o se the difference between them I'm trying to build a virtual bms an I think that somewhere I made a mistake

**Comment by dexterbg** [comment]
Kenneth,

> Sadly we have determent that the charger is broken (it's the oldest model) and that's why it doesn't work. The new problem is that we can't find a new, old one that will work with the VBMS you wrote according to what I read on your pages. (The 2016+ models)

That is not correct. All charger models are supported.

> We also tried to control the sevcon direcly with no success

You cannot operate the Twizy without the charger, as the charger runs a special Renault firmware that works as the central power up controller for the whole system. There's a chance to implement a virtual charger as well, based on the information provided here. But don't expect that to be done by me.

Regards,
Michael

**Comment by xury77** [comment]
I have same problem. Did you resolved it? 
I also have a question about 3MW relay. It should be activated (shorted C with NO) by LOW gpio3 state or HIGH? I bought one witch is activated by gnd signal. Its correct?

**Comment by dexterbg** [comment]
@xury77 The code assumes HIGH (1) to activate the relay. You can try exchanging 0/1 on all ``digitalWrite(TWIZY_3MW_CONTROL_PIN, …)`` calls if your relay needs it the other way around. You'll probably also need an init to 1 after ``pinMode(TWIZY_3MW_CONTROL_PIN, OUTPUT);``.

Regarding the fault issue, maybe @Rox50055 can provide some info on his advances.

**Comment by xury77** [comment]
Hi Michael. Could you take a look at this diagram. Is the voltage divider is correct? Or I have to swap resistors?
![multiplexer](https://user-images.githubusercontent.com/26333781/125943868-179db2d6-c509-42a5-b837-b223f50556a6.png)

**Comment by dexterbg** [comment]
Looks correct to me. Be aware the voltage divider is a rather simple monitoring approach, it didn't work very well for Klaus. Readings will be off whenever the BMS activates a cell bypass. There are better solutions based on Opamps or dedicated ICs like the LTC6803. Best option is to use a BMS that can give you the cell voltages via some communication interface.

**Comment by kosemrt** [comment]
> Kenneth,
> 
> the fault sounds like you only connected only one of the SEVCON supply relays.
> 
> I've attached a draft of the Uno example extended by the Yazaki plug and relays. Check your setup against this.
> 
> Regards, Michael
> 
> ![Arduino-Example-Yazaki-Relays](https://user-images.githubusercontent.com/2706753/78421171-eab13080-7655-11ea-9177-db2507ea21e2.png)

Hello could you share this relay' fritzing file please?

**Comment by abdurauf12345666** [comment]
I bought a Renault Tweezy without BMS and for 4 years I can’t make a virtual BMS, I can make a video on how to make your first virtual BMS based on acid batteries, I would buy a Renault Twizy accumulator, but I need to bring it from Korea if it will cost about 2000 to bring it from Korea to our country $ 3000 and in our country on average they earn $ 200 help please make a virtual BMS from acid batteries, you can throw off the connection diagram of the components

**Comment by abdurauf12345666** [comment]
please help me
