### ISSUE TITLE
Battery charge level

### ISSUE THREAD

**Issue by bakrimo** [dexterbg/Twizy-Virtual-BMS#5]
Hi friend
I did simple bms (lead acid battery)
Problem that the charge level not showing nothing
Any suggestions what I did wrong
Thanks

**Comment by dexterbg** [comment]
https://www.youtube.com/watch?v=x40XnMGI75M

**Comment by bakrimo** [comment]
Thank you for your replay
The battery level on dashboard it shows 0v charge like no battery

**Comment by dexterbg** [comment]
That's what you initially wrote. What about details like hardware setup, software configuration & serial debug log content?

**Comment by bakrimo** [comment]
What find out that the problem with hardware
Mcp2515_can bus that I have is 8mhz
Instead of 16mhz
Is there anyway to let it work with 8mhz

**Comment by dexterbg** [comment]
Looking into the configuration file may help…

https://github.com/dexterbg/Twizy-Virtual-BMS/blob/master/examples/SimpleBMS/TwizyVirtualBMS_config.h#L33

But earlier attempts with 8 MHz failed, that's why I recommend 16 MHz. You normally can exchange the crystal on an 8 MHz module.

**Comment by bakrimo** [comment]
I replaced the 8mhz crystal with 16mhz but still same problem is there anyway to get shem of Arduino nano and mcp2515 connection

**Comment by dexterbg** [comment]
I don't understand you. If there was a basic issue with your MCP2515 connection, you couldn't even switch into drive mode.

**Comment by bakrimo** [comment]
Exactly

**Comment by dexterbg** [comment]
A quick duck reveals this NiRen/Nano guide: https://circuitdigest.com/microcontroller-projects/arduino-can-tutorial-interfacing-mcp2515-can-bus-module-with-arduino

**Comment by bakrimo** [comment]
You are right was hardware problem, "Nano cheap quality built". 
Now it's showing battery level on dashboard full,  but I don't receive command from Pin9 relay sevcon supply to turn relay on
Any suggestions!

**Comment by bakrimo** [comment]
What about "ecu ok" should connect to 12v bms by 10kohm resistant or 470 ohm

**Comment by dexterbg** [comment]
Check out the example: https://github.com/dexterbg/Twizy-Virtual-BMS/blob/master/extras/Arduino-Example-Yazaki-Relays.pdf

**Comment by bakrimo** [comment]
First thank for your reply
I did this example, when I turn the ignition On it shows battery level on dashboard everything OK and N flashing. When I turn key to start position nothing happens, and I tested relay K1 sevcon supply doesn't click (doesn't receive order to work)

**Comment by bakrimo** [comment]
![IMG_20200514_172529](https://user-images.githubusercontent.com/63518889/81967462-9ff6e100-9623-11ea-9424-76373e039ba6.jpg)
That is the charger I have on twizy, you think simplebms can work with it

**Comment by dexterbg** [comment]
There are no known charger incompatibilities.

**Comment by bakrimo** [comment]
Anyway when I plug 🔌 220v the charger wouldn't give 60v to traction battery only 13.5v to the 12v battery. Does it need signal from can_bus? 
Or the charger damaged
The car locate in South korea

**Comment by dexterbg** [comment]
Yes of course it needs the CAN handshake with the BMS, that's what this project & repository is all about. See protocol documentation in the extras folder. I can only help you with the software if you provide debug details.

**Comment by bakrimo** [comment]
![IMG_20200518_123033](https://user-images.githubusercontent.com/63518889/82203001-5bad5e80-990b-11ea-8527-c7e321bbc2d6.jpg)
![IMG_20200518_123052](https://user-images.githubusercontent.com/63518889/82203011-5f40e580-990b-11ea-8107-c8de8106e149.jpg)
![IMG_20200518_123121](https://user-images.githubusercontent.com/63518889/82203024-64059980-990b-11ea-81a1-5ad196b2d993.jpg)
![IMG_20200518_123133](https://user-images.githubusercontent.com/63518889/82203032-67008a00-990b-11ea-96c7-431745386391.jpg)
Hopefully will help

**Comment by bakrimo** [comment]
Do we  have to code the BMS battery to the rest of the vehicle…charger and Inverter doesn’t recognize the BMS

**Comment by dexterbg** [comment]
Taking photos of the serial log is really weird. You can simply copy the serial log output.

But regarding the log, that looks perfectly normal & correct. So there doesn't seem to be a CAN or software issue, except if you would have configured the wrong output port for the 3MW relay. But you would already have noticed the 3MW relay doesn't work, wouldn't you?

If 3MW is OK, you should check if the CAN transmissions of the VirtualBMS really get to the bus. And you should check all charger and inverter wirings to the BMS, probably also check the relays.

**Comment by bakrimo** [comment]
Every things looks good with the wires.
But when the key on M position N keep flashing is it normal? 
And when I turn key to start position like anything at all happens

**Comment by bakrimo** [comment]
Actually 3MW relay once I turned the ignition to position ON it turned off.  the STOP LIGHT turn On WITH 3 BEEPS
