### ISSUE TITLE
Twizy battery

### ISSUE THREAD

**Issue by Tudy1983** [dexterbg/Twizy-Virtual-BMS#6]
Hi all im im new in this and I have some questions about twizy battery first in /if I take a battery from other twizy will work? Second is were I find the code? Becouse I buy all the staff to build my self one Thanks you all sorry for my bad English

**Comment by dexterbg** [comment]
1. Yes, Twizy batteries can be exchanged between vehicles.
2. See https://github.com/dexterbg/Twizy-Virtual-BMS#installation
