### ISSUE TITLE
Hi Dexter after long time 

### ISSUE THREAD

**Issue by Kamsta99** [dexterbg/Twizy-Virtual-BMS#8]
After using Twizy for 1.5 year and doing 19 500 km, i did improved Arduino project still based on SimpleBMS, with very precise voltage meter (0.03 voltage accuracy), because used way is way to unprecise to use (0.3-1v accuracy) based on voltage delivered to Arduino and temperature. I expanded project with multiple security option like 3 temperature sensors, various temperature alerts and limitations, with use of ads1115 to have precise voltage based on project: https://www.youtube.com/watch?v=10QtHh6UNBs, merged toggeder. I want send you soon my project to use :)
![223516274_174752581261186_7056948960566995612_n](https://user-images.githubusercontent.com/8656801/127406140-2a20794a-5fb9-4354-811a-b144f11ec834.jpg)
![225749656_588908008771150_4310304726786172767_n](https://user-images.githubusercontent.com/8656801/127406144-2d8932c7-6374-4e88-ad17-295e8515c87a.jpg)

I want to ask you, did its possible to control range showed in Twizy by battery ?! If yes tell me how pls :D

**Comment by dexterbg** [comment]
Nice :-)

> I want to ask you, did its possible to control range showed in Twizy by battery ?!

Not to my knowledge. AFAIR the Twizy display unit calculates the range by itself from the distance driven and the SOC consumed.

**Comment by Kamsta99** [comment]
That sad, i found that here but i dont know how interfere with that
![obraz](https://user-images.githubusercontent.com/8656801/127486833-18328af9-e7f2-49c2-bed4-6dafbd518f18.png)

**Comment by Kamsta99** [comment]
[SimpleBMS.zip](https://github.com/dexterbg/Twizy-Virtual-BMS/files/6900315/SimpleBMS.zip)

**Comment by Kamsta99** [comment]
> 
> 
> Nice :-)
> 
> > I want to ask you, did its possible to control range showed in Twizy by battery ?!
> 
> Not to my knowledge. AFAIR the Twizy display unit calculates the range by itself from the distance driven and the SOC consumed.

Problem is i drived on single charge 91 km but on display show max 30 km range

**Comment by mucahitdemir** [comment]
Hi! I think mathematical expressions for displaying _taken range_ may lead to wrong results.
In addition, can you debug this calculation by _stepping into_ function and _stepping over_ till the end?
You can track the problems on STM32 IDE or System Workbench IDE through debug options.
Best,
MD
