### ISSUE TITLE
Twizy sevcon voltage limit 

### ISSUE THREAD

**Issue by Kamsta99** [dexterbg/Twizy-Virtual-BMS#9]
Source: https://github.com/dexterbg/Twizy-Virtual-BMS/blob/master/extras/SEVCON-Configuration.md
![obraz](https://user-images.githubusercontent.com/8656801/128094876-7d26e063-7e00-4f62-888e-8d35d878b0bf.png)
I tried doing this via Ovms, no success still cutsoff after 39 V

Patient:
Twizy, 2012 ,custom 8.7 kwh battery,

What i tried already:
Setting Twizy same as for applying tuning (no switching to GO)
In shell:
1. enable <pass>
2. xrt cfg pre
3. xrt cfg write 2c02 01 592
4. xrt cfg write 2c02 02 560
5. says --> OK, value edited is same as we set
6. xrt cfg op
7. But still cutsoff, with STOP light and SEVCON low voltage error

Tried also standalone
xrt cfg write 2c02 01 592
xrt cfg write 2c02 02 560
but no clue how to get this to work

**Comment by dexterbg** [comment]
I'm afraid you're the first to actually try running the Twizy on such a low voltage. It's possible the Renault SEVCON firmware has some fixed internal limits to protect their battery, so the SDOs do not work as expected.

Another option is there is another SDO you need to change. Check out the "master dictionary" from the DVT software, maybe you can find some matching description.

**Comment by Kamsta99** [comment]
Thanks for reply, where i can get DVT software for not 500$ and stuff
needed for that also?

śr., 4 sie 2021 o 08:39 Michael Balzer ***@***.***>
napisał(a):

**Comment by Kamsta99** [comment]
Did we able to reprogram (unlock speed for example or torque) sevcon after
july 2016 with DVT software and usb dongle ?

sob., 7 sie 2021 o 13:00 Kamil Stankiewicz ***@***.***> napisał(a):

**Comment by dexterbg** [comment]
a) Search the web, b) no.
